import {
	lucideAlertCircle,
	lucideAlertTriangle,
	lucideArrowLeft,
	lucideAward,
	lucideBook,
	lucideBrain,
	lucideCalendar,
	lucideCheck,
	lucideCheckCircle2,
	lucideChevronDown,
	lucideChevronUp,
	lucideClock,
	lucideCopy,
	lucideDownload,
	lucideEye,
	lucideEyeOff,
	lucideHome,
	lucideInfo,
	lucideKey,
	lucideKeyboard,
	lucideLayoutDashboard,
	lucideLoader2,
	lucideLogOut,
	lucideMail,
	lucideMenu,
	lucideMoon,
	lucideMusic,
	lucideMusic2,
	lucidePlus,
	lucideRefreshCw,
	lucideRotateCcw,
	lucideSchool,
	lucideSearch,
	lucideSettings,
	lucideShield,
	lucideSun,
	lucideTarget,
	lucideTrash2,
	lucideTrendingUp,
	lucideTrophy,
	lucideUpload,
	lucideUser,
	lucideUserCircle,
	lucideUserMinus,
	lucideUserPlus,
	lucideUsers,
	lucideX,
} from "@ng-icons/lucide";

/**
 * Every icon the app uses, and nothing else (D12).
 *
 * The list is the exact set of names imported from `lucide-react` across
 * frontend-react/src -- 47 icons in 33 files, collected by grepping the
 * import specifiers rather than by hand. Registering the map at the root
 * (see app.config.ts) means a component only has to import `NgIcon` and
 * write `<ng-icon name="lucideSun" />`.
 *
 * Icons are decorative wherever they sit next to their own label, and
 * `<ng-icon>` sets `role="img"` on its host. Templates therefore pass
 * `aria-hidden="true"` on those, which keeps the accessibility tree the
 * same shape it had in React (lucide-react's SVGs carry no role at all).
 * The parity suite reads buttons by their accessible name, so an icon that
 * leaked into the tree would change what those selectors match.
 */
export const TREMOLO_ICONS = {
	lucideAlertCircle,
	lucideAlertTriangle,
	lucideArrowLeft,
	lucideAward,
	lucideBook,
	lucideBrain,
	lucideCalendar,
	lucideCheck,
	lucideCheckCircle2,
	lucideChevronDown,
	lucideChevronUp,
	lucideClock,
	lucideCopy,
	lucideDownload,
	lucideEye,
	lucideEyeOff,
	lucideHome,
	lucideInfo,
	lucideKey,
	lucideKeyboard,
	lucideLayoutDashboard,
	lucideLoader2,
	lucideLogOut,
	lucideMail,
	lucideMenu,
	lucideMoon,
	lucideMusic,
	lucideMusic2,
	lucidePlus,
	lucideRefreshCw,
	lucideRotateCcw,
	lucideSchool,
	lucideSearch,
	lucideSettings,
	lucideShield,
	lucideSun,
	lucideTarget,
	lucideTrash2,
	lucideTrendingUp,
	lucideTrophy,
	lucideUpload,
	lucideUser,
	lucideUserCircle,
	lucideUserMinus,
	lucideUserPlus,
	lucideUsers,
	lucideX,
};
